import React, { Component } from 'react';

export class Sitemap extends Component {
  render(){
    return(
      `<?xml version="1.0" encoding="UTF-8"?>
      <urlset
            xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/two-bedroom-suite</loc>
        </url><url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/two-bedroom-presidential-villa</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/three-bedroom-presidential-villa</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/two-bedroom-spa-suite</loc>
        </url><url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/three-bedroom-spa-suite</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/two-bedroom-residence-loft</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/three-bedroom-residence-loft</loc>
        </url><url>
          <loc>http://grandeluxxemexicojoyrentals.com/rooms/four-bedroom-residence</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/getting-here</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/dining</loc>
        </url><url>
          <loc>http://grandeluxxemexicojoyrentals.com/what-to-do</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/what-to-do/pools</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/what-to-do/activities</loc>
        </url><url>
          <loc>http://grandeluxxemexicojoyrentals.com/golf</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/spa</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/spa/spatium</loc>
        </url><url>
          <loc>http://grandeluxxemexicojoyrentals.com//spa/brio-spa</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/entertainment</loc>
        </url>
        <url>
          <loc>http://grandeluxxemexicojoyrentals.com/new-offerings</loc>
        </url>

      </urlset>`
    )
  }
}
